### ISSUE TITLE
D-flat major is wrong

### ISSUE THREAD

**Issue by sweepline** [mercvre/piano-scales#1]
The scale should be D♭, E♭, F, G♭, A♭, B♭ and C.

So the B should be moved to a C.

**Comment by mplunney** [comment]
Putting this on github was a really good idea, IMO.

**Comment by gemb0y** [comment]
> The scale should be D♭, E♭, F, G♭, A♭, B♭ and C.
> 
> So the B should be moved to a C.

Hello!

Sorry for the late answer, was quite busy lately, I'll be resolving it this week or next week.

Thank you for putting it on Github!

**Comment by gemb0y** [comment]
> Putting this on github was a really good idea, IMO.

Yes exactly! I actually put the first version on archive.org but I don't know why I didn't think about doing it on GitHub before.

**Comment by gemb0y** [comment]
Issue has been fixed.
